services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build: .
    command: python main.py
    depends_on:
      - redis

  flask-app:
    build:
      context: .
    command: python app.py
    container_name: joeynguyen/binance-api
    ports:
      - "5000:5000"
    depends_on:
      - worker
    environment:
      - REDIS_HOST=redis
